/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Solid001_1: THREE.Mesh
    Solid001_2: THREE.Mesh
  }
  materials: {
    Bianco: THREE.MeshStandardMaterial
    ['Nero.001']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Ball.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Solid001_1.geometry} material={materials.Bianco} />
      <mesh geometry={nodes.Solid001_2.geometry} material={materials['Nero.001']} />
    </group>
  )
}

useGLTF.preload('/Ball.glb')
